blank_issues_enabled: false
contact_links:
  - name: Documentation Architecture Interne
    url: https://github.com/Cedra-shop/.github/blob/main/profile/README.md
    about: Lisez la documentation système complète de Cedra-Shop.
  - name: Signaler un Incident de Sécurité Interne
    url: https://github.com/Cedra-shop/.github/blob/main/SECURITY.md
    about: Suivez notre procédure de sécurité interne pour les failles critiques. Merci de ne pas les documenter sans restriction.
